name: Deploy Application

on:
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente
    inputs:
      app:
        description: 'Nombre de la aplicación a desplegar (simple-app1 o simple-app2)'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Cambia a la versión que necesites

      - name: Terraform Init
        run: terraform init
        working-directory: ../../App/${{ github.event.inputs.app }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ../../App/${{ github.event.inputs.app }}

      - name: Wait for approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: approvalTeam

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ../../App/${{ github.event.inputs.app }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: <region>  # Cambia a tu región de AWS